import Header from "./Components/Header";
import "./globals.css";
import {Inter} from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets : ["latin"],
  weight: ["100", "200","300","400"],
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#e2e8f0] antialiased`}
      >
        {/* <Header />
        <Jat />
        <JatAbout />
        <Certifications />
        <JatBanner/>
        <Brands />
        <ProductCatergories />
        <Product/>
        <FeedbackForm /> */}

        <Header />
        
        {children}
      </body>
    </html>
  );
}
