import Header from "./Components/Header";
import "./globals.css";
import {Inter} from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets : ["latin"],
  weight: ["100", "200","300","400","500","600","700","800","900"],
})
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      
      <body
        className={`${inter.className} bg-[#e2e8f0] antialiased no-scrollbar`}
      >
        <Header />
        
        {children}
      </body>
    </html>
  );
}
